# Generated by Django 4.0.1 on 2022-01-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=32)),
                ('candidate_position', models.CharField(max_length=32)),
                ('candidate_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('votes_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=32)),
                ('candidate_name', models.CharField(max_length=32)),
                ('voter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
