# Generated by Django 4.0.1 on 2022-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_votes_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='candidate_name',
        ),
        migrations.AlterField(
            model_name='votes',
            name='position',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='voter_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
